language: go
go:
- 1.6
- tip
install:
- true
script:
- go build -ldflags "-X main.buildInfo=`git rev-parse --short HEAD`" -v -o rpiserver
deploy:
  provider: releases
  api_key:
    secure: A0JYoB4q+wAPgyYtzLUfl8bhhovjr9d45VpJ8Uw/gLi+tIYOv0Mw2SYLTj0wgwM/gJtR4r5IT0WxdCbfcgD5b3nVnolHGr78KDt+leOC+FFsPqc5pztLkfSqZl06B8OtaTplw/Hb+4sKuFEIiYyBqndUwYZe/HcYAhOh01fMYSbKDWt2Y3JWqZJrI4NlfLPownWscB2BOrK3C0hGt4M/doh8olZt1JCpfrR/r180eem3hU6srEM7z+NVBj7SyYCJPr7YQgo3ymlvtyLWw5+dhcg+Wufj4wx6lLFnhqcLMo6pHvcErxkJwRhBr/MPLlbVLFZfO+EJXJFrBfgAzVGHPQqZp4eIj6+k6eZe4XbL2WU56VORv+6AU4TclcSYMtoQ2yWgtL9sgWJAuFWZAdeQUSascBgDwgiUengtyfNkE70bdGD5hExmr0GmJBvOYFmOZ5ACufu6xwn9M+WB6qygVqL5no8dKgcEbYm8+slQa0EJzJxVcRX1XdzgkRN9HPTE+8G1v/TT3pJDxC+bDIlBl6z3kIArXOhoGWuQZmceDOWfEZ7MGtoBPJUVG/v499n02EjqGQq0FzuNvWGGPNlvnDAD9t2FgzWSEpVzn6BTaSzpUC2Msh0Q6ovtiQnAGFjl0HHXLRg/+jol6GROlQ2XGwvYm0X8k52QptJwSQfCtdc=
  file: rpiserver
  skip_cleanup: true
  on:
    repo: andreandradecosta/rpiserver
    tags: true
    go: 1.6
